import "font-awesome/css/font-awesome.min.css";
//import "../scss/atome/typography/_default.scss";
//import "../scss/molecule/stan/projectHero-module.scss";
//import "../scss/molecule/stan/ourAchievments-module.scss";
//import "../scss/molecule/stan/serviceBlock-module.scss";
// import "../scss/atome/stan/seeMore.scss";
// import "../scss/molecule/stan/reinsuranceItem.scss";
// import "../scss/molecule/stan/reinsuranceBlock.scss";
//import "../scss/molecule/stan/billetDeBlogTeaser.scss";
//import "../scss/molecule/stan/paragraphList.scss";
import "../scss/molecule/stan/pushNewsletter.scss";
